### ISSUE TITLE
lock up

### ISSUE THREAD

**Issue by mmprestine** [Engidea/FreeRoutingNew#2]
Not sure what has changed in the code base but the application freezes during routing.  If I use the freerouting jar file from the freerouting git then it runs and completes fine for the same file.  Attached test dsn renamed as png.
![test run](https://cloud.githubusercontent.com/assets/11380374/19860054/64289ac4-9f55-11e6-809a-f65ea7f2d23a.png)

**Comment by Engidea** [comment]
You mean autorouting, yes ? since normal routing (for me) works 
Also, autorouting takes a long time to "get out of freeizing", but it does eventually come out if it
(something like three/four minutes)
I must say that I have not yet found the right way to get rid of rationals and therefore have freerouting behave nicely when importing/exporting DSN (at the moment there is quite a few rounding/zapping going on, as it was before, possibly a bit less...)
Anyway, did you dig in the code or are you an "end user" ?

**Comment by mmprestine** [comment]
Yes auto routing, locks and never comes out even after 1hr.  I have not dug into the code but plan to look at it.  The base that I believe this came from seems to work fine.

**Comment by Engidea** [comment]
Did you press the left mouse button ?

**Comment by mmprestine** [comment]
yes, give it a try I attached the dsn file in the original post.

**Comment by Engidea** [comment]
While on debug I found a never ending loop and so I added some kind of termination
It is NOT a fix, it is a dirty hack but at the moment I have no time to investigate further

If you look at debug and error panels you will see that there are a few more errors logged that should be handled....
