### ISSUE TITLE
Possible regression?

### ISSUE THREAD

**Issue by aurabindo** [Engidea/FreeRoutingNew#4]
I used to route much more complex designs with Freeroute available in the repos for Fedora. But the latest git version cannot seem to complete very simple designs. Attached dsn file is a very simple one with just a USB receptacle and a chip. At 45 degree snap angle, it fails to completely route the board. I did see the warning that 45 degree snap angles are experimetal, but I never had that warning back in the old version. What am I missing ?

[new_test.dsn.zip](https://github.com/Engidea/FreeRoutingNew/files/768325/new_test.dsn.zip)

**Comment by Engidea** [comment]
![image](https://cloud.githubusercontent.com/assets/5269635/22854376/751fccbc-f06d-11e6-8de8-67d150c1a942.png)

**Comment by Engidea** [comment]
I assume you mean autoroute, yes ?
Let me explain what happens: I normally use freeroute to route boards that are not trivial, for your example board just use Kicad and you will be good. The type of boards that I do are a bit more "complicated", see www.freerouting.eu and require multiple passes from Kicad-Freeroute
Now, freeroute has a "logical" issue on how it represents traces
1) No two consecutive "points" of a trace can be colinear
2) Points in freeroute may be rational points
The above means that when you back import from Kicad a reasonably complex board you will find quite a few of "incompletes" that are quite "annoying" to fix.
So, I had to make the "autoroute" a bit "stupid" to avoid ripping up things that where basically OK and just finishing up the board incompletes.
The whole issue is far from simple, the autorouting algorithm is recursive in logic and in the standard form had quite a few possibilities of looping
So, I had to take that out to have some ind of reliable instrument, meaning that it is kind of "less intelligent" but way more reliable.
I have been trying to devise a strategy to get rid of rational points, so at least the export to Kicad is actually reliable (otherwise you get rounding issues, obviously) but the root of the issue is bound to the definition  of "equality" for a point.
The reality is that freeroute should have addressed the "problem" of rational points from the inception, trying to fix the issue later is a huge pain.
So, to make a long story short, yes, the autoroute is less intelligent, more reliable (meaning that it terminates, not that it makes good results) and generally speaking you should find that you can "route", drag things quite nicely.

**Comment by aurabindo** [comment]
@Engidea Yes, I meant the autorouter. Thanks for the explanation. It would be great if you could write a blog post on the current state of Freeroute, like a overview of the algorithm or sorts. There is a good chance of getting contributors interested. Besides, there is an increased interest in KiCad lately. Because KiCad explicitly shows support for Freeroute in the program, I think there is a good possibility of getting new contributors if you do a write up and discuss it with KiCad community.
